/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with {usernameOrEmail, password} */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and mint a new access token
         * @description The previous access token and refresh token are sent in the JSON body. The response may rotate both tokens.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's permissions and menu tree */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Permissions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MePermissions"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all of the user's refresh tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password (revokes all sessions) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordChangeRequest"];
                };
            };
            responses: {
                /** @description Changed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Validation"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List business partners */
        get: {
            parameters: {
                query?: {
                    keyword?: string;
                    isActive?: boolean;
                    pageNumber?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Business partners */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessPartnerList"];
                    };
                };
            };
        };
        put?: never;
        /** Create business partner */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BusinessPartnerCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessPartner"];
                    };
                };
                400: components["responses"]["Validation"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-partners/{businessPartnerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                businessPartnerId: string;
            };
            cookie?: never;
        };
        /** Get business partner */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    businessPartnerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Business partner */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessPartner"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update business partner */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    businessPartnerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BusinessPartnerUpdate"];
                };
            };
            responses: {
                /** @description Business partner */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessPartner"];
                    };
                };
                400: components["responses"]["Validation"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        /** Delete business partner */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    businessPartnerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents (keyset-paginated) */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    after_created_at?: components["parameters"]["AfterCreatedAt"];
                    after_id?: components["parameters"]["AfterID"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentList"];
                    };
                };
            };
        };
        put?: never;
        /** Create an agent (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgentCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** Get an agent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an agent (admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AgentPatch"];
                };
            };
            responses: {
                /** @description Agent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["Validation"];
            };
        };
        trace?: never;
    };
    "/api/agents/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** List an agent's documents (keyset-paginated) */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    after_created_at?: components["parameters"]["AfterCreatedAt"];
                    after_id?: components["parameters"]["AfterID"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Documents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentList"];
                    };
                };
            };
        };
        put?: never;
        /** Upload a document for async ingest (admin, multipart) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadAck"];
                    };
                };
                400: components["responses"]["Validation"];
                409: components["responses"]["Conflict"];
                503: components["responses"]["Unavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/documents/{docId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
                docId: components["parameters"]["PathDocID"];
            };
            cookie?: never;
        };
        /** Poll a document's ingest status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                    docId: components["parameters"]["PathDocID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a document (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                    docId: components["parameters"]["PathDocID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/kg/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** List KG dedup candidates (keyset-paginated) */
        get: {
            parameters: {
                query?: {
                    status?: components["parameters"]["StatusQuery"];
                    limit?: components["parameters"]["Limit"];
                    after_created_at?: components["parameters"]["AfterCreatedAt"];
                    after_id?: components["parameters"]["AfterID"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandidateList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/kg/graph": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** Read-only KG graph (entities as nodes, relations as edges; top-150 by confidence) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Graph */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KGGraph"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kg/candidates/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge a flagged entity pair (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MergeRequest"];
                };
            };
            responses: {
                /** @description Candidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kg/candidates/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss a flagged entity pair (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** List conversations (most-recent-first, keyset-paginated) */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    before_activity_at?: components["parameters"]["BeforeActivityAt"];
                    before_id?: components["parameters"]["BeforeID"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Conversations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** List a conversation's messages (keyset-paginated, includes summary) */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    after_created_at?: components["parameters"]["AfterCreatedAt"];
                    after_id?: components["parameters"]["AfterID"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageList"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /**
         * Current dashboard chat playground session (auto-created on first access)
         * @description Returns the operator's open scratch session for this agent plus its full thread. Playground sessions use channel='dashboard' and never appear in the conversations list or analytics.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/chat/reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the current playground session and open a fresh one */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a chat message; the reply streams back as Server-Sent Events
         * @description The response is `text/event-stream`, NOT JSON, so it is excluded from the typed TS client (the frontend reads it with fetch + a ReadableStream). Frames: repeated `event: delta` (`{text}`), then a terminal `event: done` (`{usage, finish_reason, message_id}`); on failure or a withheld (empty/blocked) reply an `event: error` (`{code, message}`) is sent and no `done` — a stream that ends without `done` means the turn failed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatMessageRequest"];
                };
            };
            responses: {
                /** @description An SSE stream of delta/done/error events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                400: components["responses"]["Validation"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["Unavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** Basic counts analytics for an agent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stats"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: {
                code?: string;
                message?: string;
            };
            statusCode?: number;
            message?: string;
            traceId?: string;
            errors?: string[];
        };
        LoginRequest: {
            usernameOrEmail: string;
            password: string;
        };
        RefreshRequest: {
            accessToken: string;
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        SuccessResponse: {
            success?: boolean;
        };
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
        };
        Session: {
            accessToken?: string;
            refreshToken?: string;
            tokenType?: string;
            expiresIn?: number;
            user?: components["schemas"]["AuthUser"];
            role?: components["schemas"]["AuthRole"];
            permissions?: string[];
        };
        AuthUser: {
            /** Format: uuid */
            id?: string;
            username?: string;
            email?: string;
            firstTimeLogin?: boolean;
        };
        AuthRole: {
            /** Format: uuid */
            id?: string;
            name?: string;
            code?: string;
        };
        Me: {
            /** Format: uuid */
            id?: string;
            username?: string;
            email?: string;
            firstTimeLogin?: boolean;
            role?: components["schemas"]["AuthRole"];
        };
        BusinessPartner: {
            /** Format: uuid */
            id?: string;
            brandName?: string;
            logoUrl?: string | null;
            email?: string;
            phone?: string;
            representativeName?: string;
            representativeEmail?: string;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string | null;
            accountCreated?: boolean | null;
            representativeEmailSent?: boolean | null;
            businessOwnerEmailSent?: boolean | null;
            usersCount?: number;
            integrationsCount?: number;
        };
        BusinessPartnerList: {
            items?: components["schemas"]["BusinessPartner"][];
            pageNumber?: number;
            pageSize?: number;
            totalCount?: number;
        };
        BusinessPartnerCreate: {
            brandName: string;
            logoUrl?: string | null;
            email: string;
            phone: string;
            representativeName: string;
            representativeEmail: string;
        };
        BusinessPartnerUpdate: {
            brandName: string;
            logoUrl?: string | null;
            email: string;
            phone: string;
            representativeName: string;
            representativeEmail: string;
            isActive: boolean;
        };
        MePermissions: {
            user?: components["schemas"]["AuthUser"];
            role?: components["schemas"]["AuthRole"];
            permissions?: string[];
            menus?: components["schemas"]["AuthMenu"][];
        };
        AuthMenu: {
            /** Format: uuid */
            featureId?: string;
            featureName?: string;
            featureCode?: string;
            displayOrder?: number;
            pages?: components["schemas"]["AuthMenuPage"][];
        };
        AuthMenuPage: {
            /** Format: uuid */
            pageId?: string;
            pageName?: string;
            pageCode?: string;
            route?: string;
            icon?: string | null;
            displayOrder?: number;
            requiredPermission?: string;
        };
        RetrievalConfig: {
            top_k?: number;
            vector_weight?: number;
            fts_weight?: number;
        };
        Agent: {
            /** Format: uuid */
            id?: string;
            agent_ref?: string;
            display_name?: string;
            system_prompt?: string;
            model?: string;
            debounce_ms?: number;
            history_turns?: number;
            max_output_tokens?: number;
            status?: string;
            retrieval_config?: components["schemas"]["RetrievalConfig"];
            kg_enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AgentCreate: {
            agent_ref: string;
            display_name?: string;
            system_prompt?: string;
            model?: string;
            debounce_ms?: number;
            history_turns?: number;
            max_output_tokens?: number;
            status?: string;
            retrieval_config?: components["schemas"]["RetrievalConfig"];
            kg_enabled?: boolean;
        };
        AgentPatch: {
            display_name?: string;
            system_prompt?: string;
            model?: string;
            debounce_ms?: number;
            history_turns?: number;
            max_output_tokens?: number;
            status?: string;
            retrieval_config?: components["schemas"]["RetrievalConfig"];
            kg_enabled?: boolean;
        };
        AgentList: {
            agents?: components["schemas"]["Agent"][];
            next_cursor?: components["schemas"]["Cursor"];
        };
        Document: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            agent_id?: string;
            title?: string;
            format?: string;
            status?: string;
            error?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        DocumentList: {
            documents?: components["schemas"]["Document"][];
            next_cursor?: components["schemas"]["Cursor"];
        };
        UploadAck: {
            /** Format: uuid */
            document_id?: string;
            status?: string;
        };
        Candidate: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            agent_id?: string;
            /** Format: uuid */
            entity_a_id?: string;
            /** Format: uuid */
            entity_b_id?: string;
            similarity?: number;
            status?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CandidateList: {
            candidates?: components["schemas"]["Candidate"][];
            next_cursor?: components["schemas"]["Cursor"];
        };
        MergeRequest: {
            /** Format: uuid */
            keep_id: string;
            /** Format: uuid */
            drop_id: string;
        };
        KGNode: {
            /** Format: uuid */
            id?: string;
            name?: string;
            entity_type?: string;
            description?: string;
            confidence?: number;
        };
        KGEdge: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            source?: string;
            /** Format: uuid */
            target?: string;
            relation_type?: string;
            confidence?: number;
        };
        KGGraph: {
            nodes?: components["schemas"]["KGNode"][];
            edges?: components["schemas"]["KGEdge"][];
            total_entities?: number;
            truncated?: boolean;
        };
        Conversation: {
            /** Format: uuid */
            id?: string;
            conversation_ref?: string;
            end_user_ref?: string;
            status?: string;
            /** Format: date-time */
            last_activity_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ConversationList: {
            conversations?: components["schemas"]["Conversation"][];
            next_cursor?: components["schemas"]["BeforeCursor"];
        };
        Message: {
            /** Format: uuid */
            id?: string;
            role?: string;
            content?: string;
            /** Format: date-time */
            created_at?: string;
        };
        MessageList: {
            /** Format: uuid */
            conversation_id?: string;
            summary?: string;
            messages?: components["schemas"]["Message"][];
            next_cursor?: components["schemas"]["Cursor"];
        };
        ChatSession: {
            conversation?: components["schemas"]["Conversation"];
            messages?: components["schemas"]["Message"][];
        };
        ChatMessageRequest: {
            text: string;
        };
        Stats: {
            documents_by_status?: {
                [key: string]: number;
            };
            conversations?: number;
            messages_30d?: number;
            kg_entities?: number;
            kg_relations?: number;
            pending_dedup?: number;
        };
        Cursor: {
            /** Format: date-time */
            after_created_at?: string;
            /** Format: uuid */
            after_id?: string;
        };
        BeforeCursor: {
            /** Format: date-time */
            before_activity_at?: string;
            /** Format: uuid */
            before_id?: string;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation failed */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Service unavailable */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PathID: string;
        PathDocID: string;
        Limit: number;
        AfterCreatedAt: string;
        AfterID: string;
        BeforeActivityAt: string;
        BeforeID: string;
        StatusQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
