/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as AppBusinessSocialMediaRouteImport } from './routes/_app/business/social-media'
import { Route as AppBusinessInformationRouteImport } from './routes/_app/business/information'
import { Route as AppAgentsNewRouteImport } from './routes/_app/agents/new'
import { Route as AppAgentsAgentIdIndexRouteImport } from './routes/_app/agents/$agentId/index'
import { Route as AppAgentsAgentIdKnowledgeIndexRouteImport } from './routes/_app/agents/$agentId/knowledge/index'
import { Route as AppAgentsAgentIdGraphIndexRouteImport } from './routes/_app/agents/$agentId/graph/index'
import { Route as AppAgentsAgentIdDocumentsIndexRouteImport } from './routes/_app/agents/$agentId/documents/index'
import { Route as AppAgentsAgentIdConversationsIndexRouteImport } from './routes/_app/agents/$agentId/conversations/index'
import { Route as AppAgentsAgentIdChatIndexRouteImport } from './routes/_app/agents/$agentId/chat/index'
import { Route as AppAgentsAgentIdAnalyticsIndexRouteImport } from './routes/_app/agents/$agentId/analytics/index'
import { Route as AppAgentsAgentIdConversationsConversationIdRouteImport } from './routes/_app/agents/$agentId/conversations/$conversationId'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessSocialMediaRoute = AppBusinessSocialMediaRouteImport.update({
  id: '/business/social-media',
  path: '/business/social-media',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessInformationRoute = AppBusinessInformationRouteImport.update({
  id: '/business/information',
  path: '/business/information',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsNewRoute = AppAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdIndexRoute = AppAgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdKnowledgeIndexRoute =
  AppAgentsAgentIdKnowledgeIndexRouteImport.update({
    id: '/agents/$agentId/knowledge/',
    path: '/agents/$agentId/knowledge/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentsAgentIdGraphIndexRoute =
  AppAgentsAgentIdGraphIndexRouteImport.update({
    id: '/agents/$agentId/graph/',
    path: '/agents/$agentId/graph/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentsAgentIdDocumentsIndexRoute =
  AppAgentsAgentIdDocumentsIndexRouteImport.update({
    id: '/agents/$agentId/documents/',
    path: '/agents/$agentId/documents/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentsAgentIdConversationsIndexRoute =
  AppAgentsAgentIdConversationsIndexRouteImport.update({
    id: '/agents/$agentId/conversations/',
    path: '/agents/$agentId/conversations/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentsAgentIdChatIndexRoute =
  AppAgentsAgentIdChatIndexRouteImport.update({
    id: '/agents/$agentId/chat/',
    path: '/agents/$agentId/chat/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentsAgentIdAnalyticsIndexRoute =
  AppAgentsAgentIdAnalyticsIndexRouteImport.update({
    id: '/agents/$agentId/analytics/',
    path: '/agents/$agentId/analytics/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAgentsAgentIdConversationsConversationIdRoute =
  AppAgentsAgentIdConversationsConversationIdRouteImport.update({
    id: '/agents/$agentId/conversations/$conversationId',
    path: '/agents/$agentId/conversations/$conversationId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/styleguide': typeof StyleguideRoute
  '/account': typeof AppAccountRoute
  '/agents/new': typeof AppAgentsNewRoute
  '/business/information': typeof AppBusinessInformationRoute
  '/business/social-media': typeof AppBusinessSocialMediaRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/agents/$agentId/conversations/$conversationId': typeof AppAgentsAgentIdConversationsConversationIdRoute
  '/agents/$agentId/analytics/': typeof AppAgentsAgentIdAnalyticsIndexRoute
  '/agents/$agentId/chat/': typeof AppAgentsAgentIdChatIndexRoute
  '/agents/$agentId/conversations/': typeof AppAgentsAgentIdConversationsIndexRoute
  '/agents/$agentId/documents/': typeof AppAgentsAgentIdDocumentsIndexRoute
  '/agents/$agentId/graph/': typeof AppAgentsAgentIdGraphIndexRoute
  '/agents/$agentId/knowledge/': typeof AppAgentsAgentIdKnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/styleguide': typeof StyleguideRoute
  '/account': typeof AppAccountRoute
  '/agents/new': typeof AppAgentsNewRoute
  '/business/information': typeof AppBusinessInformationRoute
  '/business/social-media': typeof AppBusinessSocialMediaRoute
  '/agents': typeof AppAgentsIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdIndexRoute
  '/agents/$agentId/conversations/$conversationId': typeof AppAgentsAgentIdConversationsConversationIdRoute
  '/agents/$agentId/analytics': typeof AppAgentsAgentIdAnalyticsIndexRoute
  '/agents/$agentId/chat': typeof AppAgentsAgentIdChatIndexRoute
  '/agents/$agentId/conversations': typeof AppAgentsAgentIdConversationsIndexRoute
  '/agents/$agentId/documents': typeof AppAgentsAgentIdDocumentsIndexRoute
  '/agents/$agentId/graph': typeof AppAgentsAgentIdGraphIndexRoute
  '/agents/$agentId/knowledge': typeof AppAgentsAgentIdKnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/styleguide': typeof StyleguideRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/agents/new': typeof AppAgentsNewRoute
  '/_app/business/information': typeof AppBusinessInformationRoute
  '/_app/business/social-media': typeof AppBusinessSocialMediaRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/_app/agents/$agentId/conversations/$conversationId': typeof AppAgentsAgentIdConversationsConversationIdRoute
  '/_app/agents/$agentId/analytics/': typeof AppAgentsAgentIdAnalyticsIndexRoute
  '/_app/agents/$agentId/chat/': typeof AppAgentsAgentIdChatIndexRoute
  '/_app/agents/$agentId/conversations/': typeof AppAgentsAgentIdConversationsIndexRoute
  '/_app/agents/$agentId/documents/': typeof AppAgentsAgentIdDocumentsIndexRoute
  '/_app/agents/$agentId/graph/': typeof AppAgentsAgentIdGraphIndexRoute
  '/_app/agents/$agentId/knowledge/': typeof AppAgentsAgentIdKnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/styleguide'
    | '/account'
    | '/agents/new'
    | '/business/information'
    | '/business/social-media'
    | '/agents/'
    | '/agents/$agentId/'
    | '/agents/$agentId/conversations/$conversationId'
    | '/agents/$agentId/analytics/'
    | '/agents/$agentId/chat/'
    | '/agents/$agentId/conversations/'
    | '/agents/$agentId/documents/'
    | '/agents/$agentId/graph/'
    | '/agents/$agentId/knowledge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/styleguide'
    | '/account'
    | '/agents/new'
    | '/business/information'
    | '/business/social-media'
    | '/agents'
    | '/agents/$agentId'
    | '/agents/$agentId/conversations/$conversationId'
    | '/agents/$agentId/analytics'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/conversations'
    | '/agents/$agentId/documents'
    | '/agents/$agentId/graph'
    | '/agents/$agentId/knowledge'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/styleguide'
    | '/_app/account'
    | '/_app/agents/new'
    | '/_app/business/information'
    | '/_app/business/social-media'
    | '/_app/agents/'
    | '/_app/agents/$agentId/'
    | '/_app/agents/$agentId/conversations/$conversationId'
    | '/_app/agents/$agentId/analytics/'
    | '/_app/agents/$agentId/chat/'
    | '/_app/agents/$agentId/conversations/'
    | '/_app/agents/$agentId/documents/'
    | '/_app/agents/$agentId/graph/'
    | '/_app/agents/$agentId/knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  StyleguideRoute: typeof StyleguideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/social-media': {
      id: '/_app/business/social-media'
      path: '/business/social-media'
      fullPath: '/business/social-media'
      preLoaderRoute: typeof AppBusinessSocialMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/information': {
      id: '/_app/business/information'
      path: '/business/information'
      fullPath: '/business/information'
      preLoaderRoute: typeof AppBusinessInformationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/new': {
      id: '/_app/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AppAgentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/': {
      id: '/_app/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AppAgentsAgentIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/knowledge/': {
      id: '/_app/agents/$agentId/knowledge/'
      path: '/agents/$agentId/knowledge'
      fullPath: '/agents/$agentId/knowledge/'
      preLoaderRoute: typeof AppAgentsAgentIdKnowledgeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/graph/': {
      id: '/_app/agents/$agentId/graph/'
      path: '/agents/$agentId/graph'
      fullPath: '/agents/$agentId/graph/'
      preLoaderRoute: typeof AppAgentsAgentIdGraphIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/documents/': {
      id: '/_app/agents/$agentId/documents/'
      path: '/agents/$agentId/documents'
      fullPath: '/agents/$agentId/documents/'
      preLoaderRoute: typeof AppAgentsAgentIdDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/conversations/': {
      id: '/_app/agents/$agentId/conversations/'
      path: '/agents/$agentId/conversations'
      fullPath: '/agents/$agentId/conversations/'
      preLoaderRoute: typeof AppAgentsAgentIdConversationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/chat/': {
      id: '/_app/agents/$agentId/chat/'
      path: '/agents/$agentId/chat'
      fullPath: '/agents/$agentId/chat/'
      preLoaderRoute: typeof AppAgentsAgentIdChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/analytics/': {
      id: '/_app/agents/$agentId/analytics/'
      path: '/agents/$agentId/analytics'
      fullPath: '/agents/$agentId/analytics/'
      preLoaderRoute: typeof AppAgentsAgentIdAnalyticsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId/conversations/$conversationId': {
      id: '/_app/agents/$agentId/conversations/$conversationId'
      path: '/agents/$agentId/conversations/$conversationId'
      fullPath: '/agents/$agentId/conversations/$conversationId'
      preLoaderRoute: typeof AppAgentsAgentIdConversationsConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAgentsNewRoute: typeof AppAgentsNewRoute
  AppBusinessInformationRoute: typeof AppBusinessInformationRoute
  AppBusinessSocialMediaRoute: typeof AppBusinessSocialMediaRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppAgentsAgentIdIndexRoute: typeof AppAgentsAgentIdIndexRoute
  AppAgentsAgentIdConversationsConversationIdRoute: typeof AppAgentsAgentIdConversationsConversationIdRoute
  AppAgentsAgentIdAnalyticsIndexRoute: typeof AppAgentsAgentIdAnalyticsIndexRoute
  AppAgentsAgentIdChatIndexRoute: typeof AppAgentsAgentIdChatIndexRoute
  AppAgentsAgentIdConversationsIndexRoute: typeof AppAgentsAgentIdConversationsIndexRoute
  AppAgentsAgentIdDocumentsIndexRoute: typeof AppAgentsAgentIdDocumentsIndexRoute
  AppAgentsAgentIdGraphIndexRoute: typeof AppAgentsAgentIdGraphIndexRoute
  AppAgentsAgentIdKnowledgeIndexRoute: typeof AppAgentsAgentIdKnowledgeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAgentsNewRoute: AppAgentsNewRoute,
  AppBusinessInformationRoute: AppBusinessInformationRoute,
  AppBusinessSocialMediaRoute: AppBusinessSocialMediaRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppAgentsAgentIdIndexRoute: AppAgentsAgentIdIndexRoute,
  AppAgentsAgentIdConversationsConversationIdRoute:
    AppAgentsAgentIdConversationsConversationIdRoute,
  AppAgentsAgentIdAnalyticsIndexRoute: AppAgentsAgentIdAnalyticsIndexRoute,
  AppAgentsAgentIdChatIndexRoute: AppAgentsAgentIdChatIndexRoute,
  AppAgentsAgentIdConversationsIndexRoute:
    AppAgentsAgentIdConversationsIndexRoute,
  AppAgentsAgentIdDocumentsIndexRoute: AppAgentsAgentIdDocumentsIndexRoute,
  AppAgentsAgentIdGraphIndexRoute: AppAgentsAgentIdGraphIndexRoute,
  AppAgentsAgentIdKnowledgeIndexRoute: AppAgentsAgentIdKnowledgeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  StyleguideRoute: StyleguideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
